'use strict';
const cfg=window.BUDGET_CONFIG||{}; const configured=!String(cfg.supabaseUrl).startsWith('REMPLACEZ_');
const db=configured?supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true}}):null;
const $=id=>document.getElementById(id), E={auth:$('auth'),authForm:$('authForm'),email:$('email'),password:$('password'),signup:$('signup'),authMsg:$('authMsg'),logout:$('logout'),status:$('status'),month:$('month'),add:$('add'),refresh:$('refresh'),income:$('income'),expense:$('expense'),balance:$('balance'),rate:$('rate'),rows:$('rows'),categories:$('categories'),chart:$('chart'),budget:$('budget'),saveBudget:$('saveBudget'),budgetBar:$('budgetBar'),budgetText:$('budgetText'),exportBtn:$('export'),modal:$('modal'),txForm:$('txForm'),cancel:$('cancel'),type:$('type'),date:$('date'),label:$('label'),category:$('category'),amount:$('amount')};
const CATS=['Logement','Courses','Transport','Loisirs','Abonnements','Santé','Épargne','Salaire','Autre']; let user=null, tx=[], budgetValue=0;
const euro=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(n||0); const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function initMonths(){for(let i=-18;i<=3;i++){const d=new Date();d.setDate(1);d.setMonth(d.getMonth()+i);const v=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;E.month.add(new Option(d.toLocaleDateString('fr-FR',{month:'long',year:'numeric'}),v,i===0,i===0));}E.category.innerHTML=CATS.map(x=>`<option>${x}</option>`).join('')}
async function boot(){initMonths();bind();if(!configured){E.authMsg.textContent='Configurez config.js puis publiez le dossier. Consultez README.txt.';return}const {data}=await db.auth.getSession();if(data.session) await signedIn(data.session.user);db.auth.onAuthStateChange((_e,s)=>s?signedIn(s.user):signedOut())}
function bind(){E.authForm.onsubmit=login;E.signup.onclick=signup;E.logout.onclick=()=>db.auth.signOut();E.month.onchange=loadData;E.refresh.onclick=loadData;E.add.onclick=()=>{E.txForm.reset();E.date.value=new Date().toISOString().slice(0,10);E.modal.classList.add('show')};E.cancel.onclick=()=>E.modal.classList.remove('show');E.txForm.onsubmit=addTx;E.rows.onclick=deleteTx;E.saveBudget.onclick=saveBudget;E.exportBtn.onclick=exportJson}
async function login(e){e.preventDefault();msg('Connexion…');const {error}=await db.auth.signInWithPassword({email:E.email.value,password:E.password.value});msg(error?error.message:'')}
async function signup(){msg('Création…');const {error}=await db.auth.signUp({email:E.email.value,password:E.password.value});msg(error?error.message:'Compte créé. Vérifiez éventuellement votre e-mail, puis connectez-vous.')}
function msg(x){E.authMsg.textContent=x}async function signedIn(u){user=u;E.auth.classList.remove('show');E.logout.style.display='';E.status.textContent=u.email;await loadData()}function signedOut(){user=null;E.auth.classList.add('show');E.logout.style.display='none';E.status.textContent='Déconnecté'}
async function loadData(){if(!user)return;E.status.textContent='Synchronisation…';const start=E.month.value+'-01',d=new Date(start+'T12:00:00'),end=new Date(d.getFullYear(),d.getMonth()+1,1).toISOString().slice(0,10);const [a,b]=await Promise.all([db.from('transactions').select('*').gte('tx_date',start).lt('tx_date',end).order('tx_date',{ascending:false}),db.from('monthly_budgets').select('amount').eq('month',start).maybeSingle()]);if(a.error||b.error){alert((a.error||b.error).message);E.status.textContent='Erreur';return}tx=a.data||[];budgetValue=Number(b.data?.amount||0);localStorage.setItem('budget-cache',JSON.stringify({month:E.month.value,tx,budgetValue}));E.status.textContent='Synchronisé';render()}
async function addTx(e){e.preventDefault();const row={user_id:user.id,tx_date:E.date.value,tx_type:E.type.value,label:E.label.value.trim(),category:E.category.value,amount:Number(E.amount.value)};const {error}=await db.from('transactions').insert(row);if(error)return alert(error.message);E.modal.classList.remove('show');await loadData()}
async function deleteTx(e){const b=e.target.closest('[data-id]');if(!b||!confirm('Supprimer cette opération ?'))return;const {error}=await db.from('transactions').delete().eq('id',b.dataset.id);if(error)return alert(error.message);await loadData()}
async function saveBudget(){const start=E.month.value+'-01',amount=Number(E.budget.value||0);const {error}=await db.from('monthly_budgets').upsert({user_id:user.id,month:start,amount},{onConflict:'user_id,month'});if(error)return alert(error.message);await loadData()}
function render(){const inc=tx.filter(x=>x.tx_type==='income').reduce((s,x)=>s+Number(x.amount),0),exp=tx.filter(x=>x.tx_type==='expense').reduce((s,x)=>s+Number(x.amount),0),bal=inc-exp;E.income.textContent=euro(inc);E.expense.textContent=euro(exp);E.balance.textContent=euro(bal);E.balance.className=bal>=0?'good':'bad';E.rate.textContent=inc?Math.round(bal/inc*100)+' %':'0 %';E.rows.innerHTML=tx.length?tx.map(x=>`<tr><td>${new Date(x.tx_date+'T12:00').toLocaleDateString('fr-FR')}</td><td>${esc(x.label)}</td><td><span class="pill">${esc(x.category)}</span></td><td class="amount ${x.tx_type==='income'?'good':'bad'}">${x.tx_type==='income'?'+':'-'}${euro(x.amount)}</td><td><button class="danger" data-id="${x.id}">×</button></td></tr>`).join(''):'<tr><td colspan="5" class="empty">Aucune opération</td></tr>';const by={};tx.filter(x=>x.tx_type==='expense').forEach(x=>by[x.category]=(by[x.category]||0)+Number(x.amount));E.categories.innerHTML=Object.entries(by).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<p><b>${esc(k)}</b> <span style="float:right">${euro(v)}</span></p><div class="bar"><i style="width:${exp?v/exp*100:0}%"></i></div>`).join('')||'<div class="empty">Aucune dépense</div>';E.budget.value=budgetValue||'';E.budgetBar.style.width=(budgetValue?Math.min(100,exp/budgetValue*100):0)+'%';E.budgetBar.style.background=exp>budgetValue&&budgetValue?'var(--bad)':'var(--blue)';E.budgetText.textContent=budgetValue?(exp<=budgetValue?`${euro(budgetValue-exp)} disponibles`:`Dépassement de ${euro(exp-budgetValue)}`):'Définissez un plafond.';draw()}
function draw(){const c=E.chart,g=c.getContext('2d'),w=c.width,h=c.height,p=34,d0=new Date(E.month.value+'-01T12:00'),days=new Date(d0.getFullYear(),d0.getMonth()+1,0).getDate(),vals=[];let run=0;for(let d=1;d<=days;d++){tx.filter(x=>+x.tx_date.slice(8,10)===d).forEach(x=>run+=x.tx_type==='income'?+x.amount:-x.amount);vals.push(run)}const min=Math.min(0,...vals),max=Math.max(1,...vals);g.clearRect(0,0,w,h);g.strokeStyle='#e5e7eb';g.beginPath();g.moveTo(p,h-p);g.lineTo(w-p,h-p);g.stroke();g.strokeStyle='#2563eb';g.lineWidth=3;g.beginPath();vals.forEach((v,i)=>{const x=p+i*(w-2*p)/Math.max(1,days-1),y=h-p-(v-min)/(max-min)*(h-2*p);i?g.lineTo(x,y):g.moveTo(x,y)});g.stroke();g.fillStyle='#6b7280';g.font='12px Segoe UI';g.fillText(euro(max),3,14);g.fillText(euro(min),3,h-8)}
function exportJson(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({transactions:tx,budget:budgetValue},null,2)],{type:'application/json'}));a.download='budget-'+E.month.value+'.json';a.click()}
boot();
