'use strict';

const CATS = ['Logement','Internet','Courses','Restaurant','Livraison repas','Transport','Loisirs','Jeux vidéo','Abonnements','Maison','Sport','Santé','Salaire','Épargne','Autre'];
let user=null, tx=[], annualTx=[], rules=[], auto={}, categoryBudgets=[], budgetValue=0, editTxId=null;
const cfg=window.BUDGET_CONFIG||{};
const db=!String(cfg.supabaseUrl).startsWith('REMPLACEZ_')
  ? supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true}})
  : null;
const $=id=>document.getElementById(id);
const E={auth:$('auth'),authForm:$('authForm'),email:$('email'),password:$('password'),signup:$('signup'),authMsg:$('authMsg'),logout:$('logout'),status:$('status'),month:$('month'),add:$('add'),rulesBtn:$('rulesBtn'),refresh:$('refresh'),income:$('income'),expense:$('expense'),balance:$('balance'),rate:$('rate'),rows:$('rows'),categories:$('categories'),budget:$('budget'),saveBudget:$('saveBudget'),budgetBar:$('budgetBar'),budgetText:$('budgetText'),modal:$('modal'),txForm:$('txForm'),cancel:$('cancel'),type:$('type'),date:$('date'),label:$('label'),category:$('category'),amount:$('amount'),rulesModal:$('rulesModal'),ruleForm:$('ruleForm'),ruleId:$('ruleId'),ruleKeyword:$('ruleKeyword'),ruleCategory:$('ruleCategory'),rulesList:$('rulesList'),saveRule:$('saveRule'),cancelRuleEdit:$('cancelRuleEdit'),closeRules:$('closeRules'),topExpenses:$('topExpenses'),annualChart:$('annualChart'),recurringList:$('recurringList'),forecast:$('forecast'),categoryBudgetForm:$('categoryBudgetForm'),categoryBudgetCategory:$('categoryBudgetCategory'),categoryBudgetAmount:$('categoryBudgetAmount'),categoryBudgetsList:$('categoryBudgetsList'),budgetAlerts:$('budgetAlerts')};
const euro=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(Number(n)||0);
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sum=a=>a.reduce((t,x)=>t+Number(x.amount||0),0);
const isSaving=x=>norm(x.category)==='epargne';

function injectStyles(){const style=document.createElement('style');style.textContent=`
.operation-actions{display:flex;gap:6px}.operation-actions button{padding:7px 9px}.trash-row,.history-row{display:grid;grid-template-columns:1fr auto;gap:12px;padding:12px 0;border-bottom:1px solid #e5e7eb}.warning-box{padding:12px;background:#fff7ed;color:#9a3412;border-radius:10px;margin:10px 0}.modal.show{display:flex!important}
@media(max-width:760px){html,body{max-width:100%;overflow-x:hidden}main.wrap{width:100%!important;max-width:100%!important;padding:12px!important}.cols,.cards,.toolbar{grid-template-columns:1fr!important}.card{width:100%!important;min-width:0!important}#rows,#rows tr,#rows td{display:block!important;width:100%!important}#rows tr{position:relative;margin:0 0 12px;padding:14px 52px 14px 14px;border:1px solid #e5e7eb;border-radius:12px;background:#fff}#rows td{padding:4px 0!important;border:0!important;text-align:left!important;overflow-wrap:anywhere}#rows td::before{content:attr(data-label);display:block;color:#6b7280;font-size:10px;font-weight:700;text-transform:uppercase}#rows td[data-label="Libellé"]{font-size:17px;font-weight:800}#rows td[data-label="Libellé"]::before{display:none}#rows td[data-label="Action"]{position:absolute;top:10px;right:10px;width:auto!important}.operation-actions{flex-direction:column}.operation-actions button{width:36px;height:34px;padding:0}table:has(#rows) thead{display:none}.trash-row{grid-template-columns:1fr}.trash-row>div:last-child{display:flex;gap:8px}}
`;document.head.appendChild(style);}

function createManagementUi(){if(!$('trashBtn')){const b=document.createElement('button');b.id='trashBtn';b.textContent='🗑️ Corbeille';b.className='secondary';E.refresh?.insertAdjacentElement('afterend',b);}if(!$('trashModal')){document.body.insertAdjacentHTML('beforeend',`<div id="trashModal" class="modal"><div class="dialog"><h2>🗑️ Corbeille</h2><p class="note">Les opérations supprimées restent restaurables.</p><div id="trashList"></div><div class="actions"><button id="closeTrash">Fermer</button></div></div></div>`);}$('trashBtn').onclick=openTrash;$('closeTrash').onclick=()=>$('trashModal').classList.remove('show');$('trashList').onclick=trashAction;}
function init(){injectStyles();createManagementUi();const now=new Date(),current=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;for(let y=2024;y<=2030;y++)for(let m=1;m<=12;m++){const v=`${y}-${String(m).padStart(2,'0')}`,d=new Date(y,m-1,1);E.month.add(new Option(d.toLocaleDateString('fr-FR',{month:'long',year:'numeric'}),v,v===current,v===current));}const options=CATS.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');[E.category,E.ruleCategory,E.categoryBudgetCategory].filter(Boolean).forEach(s=>s.innerHTML=options);prepareSummary();bind();}
function prepareSummary(){const chart=$('chart'),card=chart?.closest('.card');if(card)card.innerHTML='<h2>Synthèse du mois</h2><div id="monthlySummary"></div>';}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));E.authForm.onsubmit=login;E.signup.onclick=signup;E.logout.onclick=()=>db.auth.signOut();E.month.onchange=reloadAll;E.refresh.onclick=reloadAll;E.add.onclick=openAdd;E.cancel.onclick=closeTxModal;E.txForm.onsubmit=saveTx;E.rows.onclick=operationAction;E.saveBudget.onclick=saveBudget;E.categories.onclick=toggleCategory;E.label.oninput=()=>{if(!editTxId){const c=detect(E.label.value);if(CATS.includes(c))E.category.value=c;}};E.rulesBtn.onclick=async()=>{await loadRules();resetRule();E.rulesModal.classList.add('show')};E.closeRules.onclick=()=>E.rulesModal.classList.remove('show');E.ruleForm.onsubmit=saveRule;E.cancelRuleEdit.onclick=resetRule;E.rulesList.onclick=ruleAction;if(E.categoryBudgetForm)E.categoryBudgetForm.onsubmit=saveCategoryBudget;}
function showTab(name){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('[data-tab-panel]').forEach(p=>p.hidden=p.dataset.tabPanel!==name);}
async function boot(){init();if(!db){E.authMsg.textContent='Configurez config.js';return}const{data}=await db.auth.getSession();if(data.session)await signedIn(data.session.user);db.auth.onAuthStateChange((_e,s)=>s?signedIn(s.user):signedOut());}
async function login(e){e.preventDefault();const{error}=await db.auth.signInWithPassword({email:E.email.value,password:E.password.value});E.authMsg.textContent=error?.message||'';}
async function signup(){const{error}=await db.auth.signUp({email:E.email.value,password:E.password.value});E.authMsg.textContent=error?.message||'Compte créé.';}
async function signedIn(u){user=u;E.auth.classList.remove('show');E.logout.style.display='';E.status.textContent=u.email;await reloadAll();}
function signedOut(){user=null;E.auth.classList.add('show');E.logout.style.display='none';}
async function reloadAll(){if(!user)return;E.status.textContent='Synchronisation…';try{await Promise.all([loadRules(),loadMonth(),loadAnnual(),loadCategoryBudgets()]);renderAll();E.status.textContent='Synchronisé';}catch(error){console.error(error);E.status.textContent='Erreur';alert(error.message);}}
async function monthQuery(value){const start=`${value}-01`,d=new Date(`${start}T12:00`),end=new Date(d.getFullYear(),d.getMonth()+1,1).toISOString().slice(0,10);return db.from('transactions').select('*').is('deleted_at',null).gte('tx_date',start).lt('tx_date',end).order('tx_date',{ascending:false});}
async function loadMonth(){const[a,b]=await Promise.all([monthQuery(E.month.value),db.from('monthly_budgets').select('amount').eq('month',`${E.month.value}-01`).maybeSingle()]);if(a.error||b.error)throw(a.error||b.error);tx=a.data||[];budgetValue=Number(b.data?.amount||0);}
async function loadAnnual(){const y=E.month.value.slice(0,4),{data,error}=await db.from('transactions').select('*').is('deleted_at',null).gte('tx_date',`${y}-01-01`).lt('tx_date',`${Number(y)+1}-01-01`).order('tx_date');if(error)throw error;annualTx=data||[];}
async function loadRules(){const{data,error}=await db.from('category_rules').select('*').order('keyword');if(error)throw error;rules=data||[];auto={};rules.filter(r=>!r.user_id).forEach(r=>auto[norm(r.keyword)]=r.category);rules.filter(r=>r.user_id===user.id).forEach(r=>auto[norm(r.keyword)]=r.category);renderRules();}
async function loadCategoryBudgets(){if(!E.categoryBudgetsList)return;const{data,error}=await db.from('category_budgets').select('*').eq('month',`${E.month.value}-01`).order('category');if(error){console.error(error);return}categoryBudgets=data||[];}
function detect(label){const value=norm(label);for(const k of Object.keys(auto).sort((a,b)=>b.length-a.length))if(value.includes(k))return auto[k];return'';}
function openAdd(){editTxId=null;E.txForm.reset();E.date.value=new Date().toISOString().slice(0,10);const submitButton=E.txForm.querySelector('button[type="submit"], button:not([type])');if(submitButton)submitButton.textContent='Enregistrer';E.modal.classList.add('show');}
function openEdit(id){const item=tx.find(x=>x.id===id);if(!item)return;editTxId=id;E.type.value=item.tx_type;E.date.value=item.tx_date;E.label.value=item.label;E.category.value=item.category;E.amount.value=item.amount;const submitButton=E.txForm.querySelector('button[type="submit"], button:not([type])');if(submitButton)submitButton.textContent='Enregistrer les modifications';E.modal.classList.add('show');}
function closeTxModal(){editTxId=null;E.modal.classList.remove('show');}
async function findDuplicate(row){let q=db.from('transactions').select('id,tx_date,label,amount,category').is('deleted_at',null).eq('tx_date',row.tx_date).eq('tx_type',row.tx_type).eq('amount',row.amount).ilike('label',row.label);if(editTxId)q=q.neq('id',editTxId);const{data,error}=await q.limit(1);if(error)throw error;return data?.[0]||null;}
async function saveTx(e){e.preventDefault();const row={user_id:user.id,tx_date:E.date.value,tx_type:E.type.value,label:E.label.value.trim(),category:E.category.value,amount:Number(E.amount.value),updated_at:new Date().toISOString()};const duplicate=await findDuplicate(row);if(duplicate&&!confirm(`Une opération similaire existe déjà :\n${duplicate.tx_date} · ${duplicate.label} · ${euro(duplicate.amount)}\n\nEnregistrer quand même ?`))return;if(editTxId){const{error}=await db.from('transactions').update(row).eq('id',editTxId);if(error)return alert(error.message);}else{const{error}=await db.from('transactions').insert(row);if(error)return alert(error.message);if(row.tx_type==='expense'&&!detect(row.label)){const proposed=prompt(`Créer une règle automatique pour « ${row.label} » ?\nCatégorie : ${row.category}`,norm(row.label).split(/\s+/)[0]);if(proposed)await db.from('category_rules').insert({user_id:user.id,keyword:norm(proposed),category:row.category});}}closeTxModal();await reloadAll();}
async function operationAction(e){const edit=e.target.closest('[data-edit-tx]'),del=e.target.closest('[data-delete-tx]');if(edit)openEdit(edit.dataset.editTx);if(del&&confirm('Déplacer cette opération dans la corbeille ?')){const{error}=await db.from('transactions').update({deleted_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',del.dataset.deleteTx);if(error)return alert(error.message);await reloadAll();}}
async function openTrash(){const{data,error}=await db.from('transactions').select('*').not('deleted_at','is',null).order('deleted_at',{ascending:false});if(error)return alert(error.message);$('trashList').innerHTML=data.length?data.map(x=>`<div class="trash-row"><div><b>${esc(x.label)}</b><small class="note" style="display:block">${x.tx_date} · ${esc(x.category)} · ${euro(x.amount)}</small></div><div><button data-restore="${x.id}">Restaurer</button><button class="danger" data-purge="${x.id}">Supprimer définitivement</button></div></div>`).join(''):'<div class="empty">Corbeille vide</div>';$('trashModal').classList.add('show');}
async function trashAction(e){const restore=e.target.closest('[data-restore]'),purge=e.target.closest('[data-purge]');if(restore){await db.from('transactions').update({deleted_at:null,updated_at:new Date().toISOString()}).eq('id',restore.dataset.restore);await openTrash();await reloadAll();}if(purge&&confirm('Suppression définitive. Continuer ?')){await db.from('transactions').delete().eq('id',purge.dataset.purge);await openTrash();}}
async function saveBudget(){const{error}=await db.from('monthly_budgets').upsert({user_id:user.id,month:`${E.month.value}-01`,amount:Number(E.budget.value||0)},{onConflict:'user_id,month'});if(error)return alert(error.message);await reloadAll();}
async function saveCategoryBudget(e){e.preventDefault();const{error}=await db.from('category_budgets').upsert({user_id:user.id,month:`${E.month.value}-01`,category:E.categoryBudgetCategory.value,amount:Number(E.categoryBudgetAmount.value||0)},{onConflict:'user_id,month,category'});if(error)return alert(error.message);await reloadAll();}
function resetRule(){E.ruleForm.reset();E.ruleId.value='';E.saveRule.textContent='Ajouter';E.cancelRuleEdit.style.display='none';}
function renderRules(){if(!E.rulesList)return;E.rulesList.innerHTML=rules.map(r=>{const own=r.user_id===user?.id;return`<div class="rule-row"><div><b>${esc(r.keyword)}</b><small>${own?'Personnelle':'Globale'}</small></div><span>${esc(r.category)}</span><span>${own?`<button data-edit="${r.id}">✏️</button><button data-delete="${r.id}">🗑️</button>`:'🔒'}</span></div>`}).join('');}
async function saveRule(e){e.preventDefault();const keyword=norm(E.ruleKeyword.value),category=E.ruleCategory.value,id=E.ruleId.value;const q=id?db.from('category_rules').update({keyword,category}).eq('id',id).eq('user_id',user.id):db.from('category_rules').insert({user_id:user.id,keyword,category});const{error}=await q;if(error)return alert(error.message);resetRule();await reloadAll();}
async function ruleAction(e){const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(edit){const r=rules.find(x=>x.id===edit.dataset.edit);E.ruleId.value=r.id;E.ruleKeyword.value=r.keyword;E.ruleCategory.value=r.category;E.saveRule.textContent='Enregistrer';E.cancelRuleEdit.style.display='';}if(del&&confirm('Supprimer cette règle ?')){await db.from('category_rules').delete().eq('id',del.dataset.delete).eq('user_id',user.id);await reloadAll();}}
function metrics(items){const income=sum(items.filter(x=>x.tx_type==='income')),savings=sum(items.filter(x=>x.tx_type==='expense'&&isSaving(x))),spending=sum(items.filter(x=>x.tx_type==='expense'&&!isSaving(x)));return{income,savings,spending,balance:income-spending-savings,rate:income?savings/income*100:0};}
function grouped(items){const g={};items.filter(x=>x.tx_type==='expense').forEach(x=>{g[x.category]??={total:0,details:{}};g[x.category].total+=Number(x.amount);g[x.category].details[x.label]=(g[x.category].details[x.label]||0)+Number(x.amount)});return g;}
function renderAll(){renderHome();renderSummary();renderRecurring();renderAnalysis();renderCategoryBudgets();}
function renderHome(){const m=metrics(tx);E.income.textContent=euro(m.income);E.expense.textContent=euro(m.spending);E.balance.textContent=euro(m.balance);E.balance.className=m.balance>=0?'good':'bad';E.rate.textContent=`${Math.round(m.rate)} %`;E.rows.innerHTML=tx.length?tx.map(x=>`<tr><td data-label="Date">${new Date(`${x.tx_date}T12:00`).toLocaleDateString('fr-FR')}</td><td data-label="Libellé">${esc(x.label)}</td><td data-label="Catégorie"><span class="pill">${esc(x.category)}</span></td><td data-label="Montant" class="amount ${x.tx_type==='income'?'good':'bad'}">${x.tx_type==='income'?'+':'-'}${euro(x.amount)}</td><td data-label="Action"><div class="operation-actions"><button data-edit-tx="${x.id}" title="Modifier">✏️</button><button class="danger" data-delete-tx="${x.id}" title="Corbeille">🗑️</button></div></td></tr>`).join(''):'<tr><td colspan="5" class="empty">Aucune opération</td></tr>';const g=grouped(tx),total=Object.values(g).reduce((t,x)=>t+x.total,0);E.categories.innerHTML=Object.entries(g).sort((a,b)=>b[1].total-a[1].total).map(([c,v],i)=>`<div><button data-cat="d${i}" style="width:100%;text-align:left;border:0"><b>▶ ${esc(c)}</b><span style="float:right">${euro(v.total)} · ${total?Math.round(v.total/total*100):0}%</span></button><div class="bar"><i style="width:${total?v.total/total*100:0}%"></i></div><div id="d${i}" hidden>${Object.entries(v.details).map(([l,a])=>`<div style="display:flex;justify-content:space-between"><span>${esc(l)}</span><span>${euro(a)} · ${Math.round(a/v.total*100)}%</span></div>`).join('')}</div></div>`).join('');E.budget.value=budgetValue||'';E.budgetBar.style.width=`${budgetValue?Math.min(100,m.spending/budgetValue*100):0}%`;E.budgetText.textContent=budgetValue?`${euro(budgetValue-m.spending)} disponibles`:'Définissez un plafond.';}
function toggleCategory(e){const b=e.target.closest('[data-cat]');if(!b)return;const d=$(b.dataset.cat);d.hidden=!d.hidden;}
function renderSummary(){const target=$('monthlySummary');if(!target)return;const m=metrics(tx),top=[...tx].filter(x=>x.tx_type==='expense'&&!isSaving(x)).sort((a,b)=>Number(b.amount)-Number(a.amount))[0];target.innerHTML=`<div class="summary-cards" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:12px"><div><small>Épargne</small><strong>${euro(m.savings)}</strong></div><div><small>Opérations</small><strong>${tx.length}</strong></div><div><small>${m.balance>=0?'Budget maîtrisé':'Déficit'}</small><strong class="${m.balance>=0?'good':'bad'}">${euro(m.balance)}</strong></div><div><small>Plus grosse dépense</small><strong>${top?`${esc(top.label)} · ${euro(top.amount)}`:'-'}</strong></div></div>`;}
function renderRecurring(){if(!E.recurringList)return;const g={};annualTx.filter(x=>x.tx_type==='expense').forEach(x=>{const k=norm(x.label);g[k]??={label:x.label,category:x.category,entries:[]};g[k].entries.push({amount:Number(x.amount),date:x.tx_date,month:x.tx_date.slice(0,7)})});const list=Object.values(g).map(x=>{x.entries.sort((a,b)=>a.date.localeCompare(b.date));const months=new Set(x.entries.map(e=>e.month)),latest=x.entries.at(-1)?.amount||0,prev=x.entries.at(-2)?.amount??latest,average=x.entries.reduce((t,e)=>t+e.amount,0)/x.entries.length;return{...x,months:months.size,latest,average,variation:latest-prev}}).filter(x=>x.months>=2);E.recurringList.innerHTML=list.length?list.map(x=>`<div class="recurring-row"><div><b>${esc(x.label)}</b><small>${esc(x.category)} · ${x.months} mois</small><small>${x.variation===0?'Stable':`${x.variation>0?'+':''}${euro(x.variation)} vs précédent`}</small></div><div><strong>${euro(x.latest)}</strong><small>Dernier montant</small><small>Moyenne ${euro(x.average)}</small></div></div>`).join(''):'<div class="empty">Aucune récurrence</div>';}
function renderAnalysis(){if(E.topExpenses){const top=[...tx].filter(x=>x.tx_type==='expense'&&!isSaving(x)).sort((a,b)=>b.amount-a.amount).slice(0,5);E.topExpenses.innerHTML=top.map((x,i)=>`<div class="rank-row"><b>${i+1}. ${esc(x.label)}</b><span>${euro(x.amount)}</span></div>`).join('');}if(E.forecast){const m=metrics(tx),d=new Date(`${E.month.value}-01T12:00`),now=new Date(),days=new Date(d.getFullYear(),d.getMonth()+1,0).getDate(),elapsed=d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()?now.getDate():days;E.forecast.innerHTML=`<div class="forecast-value">${euro(m.spending/Math.max(1,elapsed)*days)}</div><p>Projection fin de mois</p>`;}renderAnnualBalances();}
function renderAnnualBalances(){if(!E.annualChart)return;const card=E.annualChart.closest('.card');if(!$('annualBalanceList'))card.innerHTML='<h2>Historique des soldes mensuels</h2><div id="annualBalanceList"></div>';const y=Number(E.month.value.slice(0,4)),months=Array.from({length:12},(_,i)=>({i,income:0,spending:0,savings:0}));annualTx.forEach(x=>{const i=Number(x.tx_date.slice(5,7))-1,a=Number(x.amount);if(x.tx_type==='income')months[i].income+=a;else if(isSaving(x))months[i].savings+=a;else months[i].spending+=a});$('annualBalanceList').innerHTML=months.map(m=>{const b=m.income-m.spending-m.savings,name=new Date(y,m.i,1).toLocaleDateString('fr-FR',{month:'long'});return`<div class="annual-balance-row"><div><b>${name}</b><small>${m.income||m.spending||m.savings?`Revenus ${euro(m.income)} · Dépenses ${euro(m.spending)} · Épargne ${euro(m.savings)}`:'Aucune opération'}</small></div><strong class="${b>=0?'good':'bad'}">${b>=0?'🟢 +':'🔴 '}${euro(b)}</strong></div>`}).join('');}
function renderCategoryBudgets(){if(!E.categoryBudgetsList)return;const g=grouped(tx);E.categoryBudgetsList.innerHTML=categoryBudgets.length?categoryBudgets.map(x=>{const spent=g[x.category]?.total||0,p=x.amount?spent/x.amount*100:0;return`<div class="category-budget-row"><b>${esc(x.category)}</b><span>${euro(spent)} / ${euro(x.amount)}</span><div class="bar"><i style="width:${Math.min(100,p)}%"></i></div></div>`}).join(''):'<div class="empty">Aucun budget par catégorie</div>';}
boot();
